name: sgan
channels:
  - conda-forge
  - defaults
dependencies:
  - contextlib2=0.6.0
  - flake8=3.7.9
  - future=0.18.2
  - ipython=7.13.0
  - numpy=1.16.4
  - opt-einsum=2.3.2
  - pip=20.0.2
  - pyflakes=2.1.1
  - pynvim=0.4.1
  - python=3.6.10
  - tensorboard=1.14.0
  - tensorflow-base=1.14.0=gpu_py36he45bfe2_0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - tensorflow-hub=0.6.0
  - tensorflow-probability=0.7
  - tqdm=4.43.0
  - yapf=0.29.0
  - pip:
    - dm-sonnet==1.34
    - tensorflow-gan==1.0.0.dev0
    - tensorflow-io==0.7.0
